"""add_batch_pricing_and_selected_batch

Revision ID: 04b13e8c498e
Revises: e84525e94a76
Create Date: 2026-09-09 23:51:20.322106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04b13e8c498e'
down_revision: Union[str, None] = 'e84525e94a76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_batch_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_order_items_selected_batch_id'), ['selected_batch_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_order_items_selected_batch_id_stock_intakes'), 'stock_intakes', ['selected_batch_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('stock_intakes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retail_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('mrp', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('wholesale_price', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_intakes', schema=None) as batch_op:
        batch_op.drop_column('wholesale_price')
        batch_op.drop_column('mrp')
        batch_op.drop_column('retail_price')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_order_items_selected_batch_id_stock_intakes'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_order_items_selected_batch_id'))
        batch_op.drop_column('selected_batch_id')

    # ### end Alembic commands ###
