"""Add customer_id to Order

Revision ID: 06a7dfcb3a91
Revises: 0d8b1e193721
Create Date: 2026-08-22 16:39:31.483211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06a7dfcb3a91'
down_revision: Union[str, None] = '0d8b1e193721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_customer_id'), ['customer_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_orders_customer_id_customers'), 'customers', ['customer_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_orders_customer_id_customers'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_orders_customer_id'))
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
