"""add invoice terms

Revision ID: 0d8b1e193721
Revises: 631a5a93be73
Create Date: 2026-08-22 01:46:57.953161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d8b1e193721'
down_revision: Union[str, None] = '631a5a93be73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_terms_conditions', sa.String(length=2000), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.drop_column('invoice_terms_conditions')

    # ### end Alembic commands ###
