"""add evening_pricing_mode to outlets

Revision ID: 3fc33ca8be24
Revises: 9e5092351104
Create Date: 2026-08-17 02:00:31.914876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fc33ca8be24'
down_revision: Union[str, None] = '9e5092351104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evening_pricing_mode', sa.String(length=20), server_default='OFF', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.drop_column('evening_pricing_mode')

    # ### end Alembic commands ###
