"""Add CashDrawerLedger table

Revision ID: 49b1ee60968c
Revises: a4f96c36795a
Create Date: 2026-09-02 03:36:30.752553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49b1ee60968c'
down_revision: Union[str, None] = 'a4f96c36795a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
