"""add_shelf_life_alerts

Revision ID: 4a2902ecdde3
Revises: 06a7dfcb3a91
Create Date: 2026-08-23 10:26:32.927085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a2902ecdde3'
down_revision: Union[str, None] = '06a7dfcb3a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shelf_life_alert_hrs', sa.Integer(), nullable=True))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.Enum('NEAR_EXPIRY', 'LOW_STOCK', 'RETURN_REQUEST', 'ABANDONED_CART', 'PRICE_ALERT', 'SHELF_LIFE_ALERT', name='notificationtypeenum'),
               existing_nullable=False)

    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_emails', sa.JSON(), server_default='[]', nullable=False))
        batch_op.add_column(sa.Column('notification_phones', sa.JSON(), server_default='[]', nullable=False))
        batch_op.drop_column('notification_email')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_email', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('notification_phones')
        batch_op.drop_column('notification_emails')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('NEAR_EXPIRY', 'LOW_STOCK', 'RETURN_REQUEST', 'ABANDONED_CART', 'PRICE_ALERT', 'SHELF_LIFE_ALERT', name='notificationtypeenum'),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_column('shelf_life_alert_hrs')

    # ### end Alembic commands ###
