"""add loyalty_discount_inr

Revision ID: 4a8d6babd123
Revises: 729b94f914eb
Create Date: 2026-09-05 20:27:42.932281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a8d6babd123'
down_revision: Union[str, None] = '729b94f914eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loyalty_discount_inr', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('loyalty_discount_inr')

    # ### end Alembic commands ###
