"""Add returned_quantity to OrderItem

Revision ID: 4b4a463fe612
Revises: 49b1ee60968c
Create Date: 2026-09-02 10:06:08.753346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b4a463fe612'
down_revision: Union[str, None] = '49b1ee60968c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('returned_quantity', sa.Numeric(precision=10, scale=3), server_default='0.00', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('returned_quantity')

    # ### end Alembic commands ###
