"""Add replaces_bill_id to Order

Revision ID: 5716cbf3a573
Revises: 0628f888ecfc
Create Date: 2026-09-03 00:38:55.986745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5716cbf3a573'
down_revision: Union[str, None] = '0628f888ecfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('replaces_bill_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_replaces_bill_id'), ['replaces_bill_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_orders_replaces_bill_id_orders'), 'orders', ['replaces_bill_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_orders_replaces_bill_id_orders'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_orders_replaces_bill_id'))
        batch_op.drop_column('replaces_bill_id')

    # ### end Alembic commands ###
