"""Add supplier_id to stock_intakes

Revision ID: 5ef4b84d4996
Revises: c182feef3377
Create Date: 2026-09-02 01:36:58.726784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef4b84d4996'
down_revision: Union[str, None] = 'c182feef3377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_intakes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_stock_intakes_supplier_id_suppliers'), 'suppliers', ['supplier_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('supplier_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_intakes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_name', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_stock_intakes_supplier_id_suppliers'), type_='foreignkey')
        batch_op.drop_column('supplier_id')

    # ### end Alembic commands ###
