"""Add loyalty points feature

Revision ID: 631a5a93be73
Revises: d932febf71c4
Create Date: 2026-08-21 23:58:19.349753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '631a5a93be73'
down_revision: Union[str, None] = 'd932febf71c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loyalty_points', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loyalty_points_earned', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('loyalty_points_redeemed', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loyalty_points_per_100_inr', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('loyalty_point_value_inr', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.drop_column('loyalty_point_value_inr')
        batch_op.drop_column('loyalty_points_per_100_inr')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('loyalty_points_redeemed')
        batch_op.drop_column('loyalty_points_earned')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('loyalty_points')

    # ### end Alembic commands ###
