"""Add credit_cashed_out to Order

Revision ID: 729b94f914eb
Revises: a903ecc815b8
Create Date: 2026-09-05 17:35:23.984082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '729b94f914eb'
down_revision: Union[str, None] = 'a903ecc815b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_cashed_out', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('credit_cashed_out')

    # ### end Alembic commands ###
