"""Add loyalty tiers and max bill percentage

Revision ID: 8207fa25df2c
Revises: a447281032e6
Create Date: 2026-09-02 13:45:41.477839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8207fa25df2c'
down_revision: Union[str, None] = 'a447281032e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loyalty_redemption_tiers', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('loyalty_max_bill_percentage', sa.Numeric(precision=5, scale=2), server_default='100.00', nullable=False))
        batch_op.drop_column('loyalty_point_value_inr')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loyalty_point_value_inr', sa.NUMERIC(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=False))
        batch_op.drop_column('loyalty_max_bill_percentage')
        batch_op.drop_column('loyalty_redemption_tiers')

    # ### end Alembic commands ###
