"""add_customer_credit_debit

Revision ID: 8a82a16efc49
Revises: 8215bd1a6282
Create Date: 2026-09-04 16:24:34.144889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a82a16efc49'
down_revision: Union[str, None] = '8215bd1a6282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('outlet_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('entry_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_by_staff_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_staff_id'], ['users.id'], name=op.f('fk_customer_ledger_created_by_staff_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_ledger_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_customer_ledger_order_id_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], name=op.f('fk_customer_ledger_outlet_id_outlets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_ledger'))
    )
    with op.batch_alter_table('customer_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_ledger_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_ledger_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_ledger_outlet_id'), ['outlet_id'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_balance', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_applied', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))
        batch_op.add_column(sa.Column('debit_applied', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('debit_applied')
        batch_op.drop_column('credit_applied')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('credit_balance')

    with op.batch_alter_table('customer_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_ledger_outlet_id'))
        batch_op.drop_index(batch_op.f('ix_customer_ledger_order_id'))
        batch_op.drop_index(batch_op.f('ix_customer_ledger_customer_id'))

    op.drop_table('customer_ledger')
    # ### end Alembic commands ###
