"""add weighing scale format to outlet

Revision ID: 9cb83343ee1b
Revises: 5716cbf3a573
Create Date: 2026-09-03 02:17:20.609973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cb83343ee1b'
down_revision: Union[str, None] = '5716cbf3a573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weighing_scale_barcode_format', sa.String(length=50), server_default='21_5I_5W_GRAMS', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.drop_column('weighing_scale_barcode_format')

    # ### end Alembic commands ###
