"""add evening auto schedule to outlets

Revision ID: 9e5092351104
Revises: e5c3b34cf940
Create Date: 2026-08-16 23:15:08.580064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e5092351104'
down_revision: Union[str, None] = 'e5c3b34cf940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evening_auto_enabled', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('evening_auto_start_time', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('evening_auto_end_time', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.drop_column('evening_auto_end_time')
        batch_op.drop_column('evening_auto_start_time')
        batch_op.drop_column('evening_auto_enabled')

    # ### end Alembic commands ###
