"""Add complimentary_items to BillDiscountApproval

Revision ID: a447281032e6
Revises: 4b4a463fe612
Create Date: 2026-09-02 11:24:47.943769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a447281032e6'
down_revision: Union[str, None] = '4b4a463fe612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_discount_approvals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complimentary_items', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_discount_approvals', schema=None) as batch_op:
        batch_op.drop_column('complimentary_items')

    # ### end Alembic commands ###
