"""Add CashDrawerLedger and Order.change_denominations

Revision ID: a4f96c36795a
Revises: 5ef4b84d4996
Create Date: 2026-09-02 03:34:50.077755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4f96c36795a'
down_revision: Union[str, None] = '5ef4b84d4996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('change_denominations', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('change_denominations')

    # ### end Alembic commands ###
