"""Add margin configuration to inventory items

Revision ID: c182feef3377
Revises: 4a2902ecdde3
Create Date: 2026-09-01 18:42:07.458380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c182feef3377'
down_revision: Union[str, None] = '4a2902ecdde3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retail_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('margin_type', sa.Enum('MARKUP', 'MARGIN', name='margintypeenum'), server_default='MARKUP', nullable=False))
        batch_op.add_column(sa.Column('retail_margin_pct', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('mrp_margin_pct', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('wholesale_margin_pct', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_column('wholesale_margin_pct')
        batch_op.drop_column('mrp_margin_pct')
        batch_op.drop_column('retail_margin_pct')
        batch_op.drop_column('margin_type')
        batch_op.drop_column('retail_price')

    # ### end Alembic commands ###
