"""add_email_billqr_placeofsupply_delivery_handling

Revision ID: d932febf71c4
Revises: 8f72fcc1185e
Create Date: 2026-08-21 22:29:23.815434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'd932febf71c4'
down_revision: Union[str, None] = '8f72fcc1185e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('local_action_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_local_action_queue_client_action_id'))

    op.drop_table('local_action_queue')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_charge', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))
        batch_op.add_column(sa.Column('handling_charge', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))

    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bill_qr_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('place_of_supply', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.drop_column('place_of_supply')
        batch_op.drop_column('bill_qr_url')
        batch_op.drop_column('email')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('handling_charge')
        batch_op.drop_column('delivery_charge')

    op.create_table('local_action_queue',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('client_action_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('action_timestamp', sa.DATETIME(), nullable=False),
    sa.Column('payload', sqlite.JSON(), nullable=True),
    sa.Column('synced', sa.BOOLEAN(), server_default=sa.text("'false'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_local_action_queue'))
    )
    with op.batch_alter_table('local_action_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_local_action_queue_client_action_id'), ['client_action_id'], unique=1)

    # ### end Alembic commands ###
