"""Add credit_awarded to Order

Revision ID: e03724b88bc3
Revises: 5376849d5f3b
Create Date: 2026-09-04 18:04:50.871699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e03724b88bc3'
down_revision: Union[str, None] = '5376849d5f3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_awarded', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('credit_awarded')

    # ### end Alembic commands ###
