"""add extra_detail to customers

Revision ID: e5a814a7ce57
Revises: 4a8d6babd123
Create Date: 2026-09-06 03:12:20.074046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5a814a7ce57'
down_revision: Union[str, None] = '4a8d6babd123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_detail', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('extra_detail')

    # ### end Alembic commands ###
