"""Add fields to Supplier model

Revision ID: e992afa3c1c8
Revises: 9cb83343ee1b
Create Date: 2026-09-03 14:55:24.965883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e992afa3c1c8'
down_revision: Union[str, None] = '9cb83343ee1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gstin', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('contact_person', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_terms', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('payment_terms')
        batch_op.drop_column('contact_person')
        batch_op.drop_column('gstin')

    # ### end Alembic commands ###
