"""initial_schema

Revision ID: f85e00d392cf
Revises: 
Create Date: 2026-08-14 21:22:27.920012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f85e00d392cf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outlets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('payment_mode', sa.Enum('RAZORPAY_GATEWAY', 'PAY_AT_COUNTER', 'BOTH', name='paymentmodeenum'), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('gstin', sa.String(length=50), nullable=True),
    sa.Column('fssai_no', sa.String(length=50), nullable=True),
    sa.Column('direct_upi_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_account_id', sa.String(length=100), nullable=True),
    sa.Column('raw_upi_payload', sa.String(length=500), nullable=True),
    sa.Column('session_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('session_grace_period_minutes', sa.Integer(), nullable=False),
    sa.Column('public_basket_number', sa.String(length=50), nullable=True),
    sa.Column('verification_amount_cutoff', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('flagged_item_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outlets'))
    )
    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outlets_slug'), ['slug'], unique=True)

    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events'))
    )
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_events_event_id'), ['event_id'], unique=True)

    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('outlet_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], name=op.f('fk_categories_outlet_id_outlets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('outlet_id', 'name', name='uq_categories_outlet_id_name')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_outlet_id'), ['outlet_id'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('outlet_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], name=op.f('fk_customers_outlet_id_outlets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('outlet_id', 'phone', name='uq_customers_outlet_phone')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_outlet_id'), ['outlet_id'], unique=False)

    op.create_table('inventory_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('outlet_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.Enum('KG', 'G', 'L', 'ML', 'PCS', name='inventoryunitenum'), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('current_stock', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('reorder_threshold', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('cost_per_unit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mrp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('wholesale_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_category', sa.String(length=100), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], name=op.f('fk_inventory_items_outlet_id_outlets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_items')),
    sa.UniqueConstraint('outlet_id', 'name', name='uq_inventory_items_outlet_id_name')
    )
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_items_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_items_outlet_id'), ['outlet_id'], unique=False)

    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('outlet_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], name=op.f('fk_suppliers_outlet_id_outlets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers')),
    sa.UniqueConstraint('outlet_id', 'name', name='uq_suppliers_outlet_id_name')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_outlet_id'), ['outlet_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('outlet_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Enum('SUPERADMIN', 'OUTLET_ADMIN', 'MANAGER', 'FLOOR_STAFF', 'CASHIER', 'WAITER', 'DELIVERY_BOY', 'STAFF', name='roleenum'), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], name=op.f('fk_users_outlet_id_outlets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_outlet_id'), ['outlet_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('outlet_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], name=op.f('fk_audit_logs_outlet_id_outlets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_outlet_id'), ['outlet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('basket_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('outlet_id', sa.UUID(), nullable=False),
    sa.Column('basket_number', sa.String(length=50), nullable=False),
    sa.Column('session_key', sa.String(length=512), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'EXPIRED', 'TERMINATED', name='sessionstatusenum'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('terminated_by_id', sa.UUID(), nullable=True),
    sa.Column('termination_reason', sa.String(length=500), nullable=True),
    sa.Column('terminated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_basket_sessions_customer_id_customers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], name=op.f('fk_basket_sessions_outlet_id_outlets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['terminated_by_id'], ['users.id'], name=op.f('fk_basket_sessions_terminated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_basket_sessions'))
    )
    with op.batch_alter_table('basket_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_basket_sessions_outlet_id'), ['outlet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_basket_sessions_session_key'), ['session_key'], unique=True)

    op.create_table('menu_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('outlet_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_on_offer', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_verification_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('offer_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('offer_label', sa.String(length=255), nullable=True),
    sa.Column('mrp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('wholesale_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_category', sa.String(length=100), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pricing_mode', sa.Enum('WEIGHT_BASED', 'FIXED_UNIT', name='pricingmodeenum'), server_default='FIXED_UNIT', nullable=False),
    sa.Column('unit_label', sa.String(length=50), server_default='piece', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_menu_items_category_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], name=op.f('fk_menu_items_inventory_item_id_inventory_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], name=op.f('fk_menu_items_outlet_id_outlets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_items'))
    )
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menu_items_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_items_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_items_inventory_item_id'), ['inventory_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_items_outlet_id'), ['outlet_id'], unique=False)

    op.create_table('staff',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('outlet_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('SUPERADMIN', 'OUTLET_ADMIN', 'MANAGER', 'FLOOR_STAFF', 'CASHIER', 'WAITER', 'DELIVERY_BOY', 'STAFF', name='roleenum'), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('pin_hash', sa.String(length=512), nullable=True),
    sa.Column('refresh_token_hash', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_staff_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], name=op.f('fk_staff_outlet_id_outlets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff'))
    )
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_outlet_id'), ['outlet_id'], unique=False)

    op.create_table('stock_intakes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('outlet_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('initial_quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('remaining_quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('intake_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('added_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_stock_intakes_added_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], name=op.f('fk_stock_intakes_item_id_inventory_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], name=op.f('fk_stock_intakes_outlet_id_outlets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_intakes'))
    )
    with op.batch_alter_table('stock_intakes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_intakes_batch_number'), ['batch_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_intakes_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_intakes_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_intakes_outlet_id'), ['outlet_id'], unique=False)

    op.create_table('menu_item_recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('menu_item_id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('quantity_required', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.Enum('KG', 'G', 'L', 'ML', 'PCS', name='inventoryunitenum'), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], name=op.f('fk_menu_item_recipes_inventory_item_id_inventory_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name=op.f('fk_menu_item_recipes_menu_item_id_menu_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_item_recipes'))
    )
    with op.batch_alter_table('menu_item_recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menu_item_recipes_inventory_item_id'), ['inventory_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_item_recipes_menu_item_id'), ['menu_item_id'], unique=False)

    op.create_table('menu_item_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('menu_item_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price_delta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name=op.f('fk_menu_item_variants_menu_item_id_menu_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_item_variants'))
    )
    with op.batch_alter_table('menu_item_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menu_item_variants_menu_item_id'), ['menu_item_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('outlet_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('basket_number', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PENDING_VERIFICATION', 'PAID', 'PAYMENT_PENDING', 'COMPLETED', 'CANCELLED', 'REFUNDED', name='orderstatusenum'), nullable=False),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('is_auto_verified', sa.Boolean(), nullable=False),
    sa.Column('created_by_staff_id', sa.UUID(), nullable=True),
    sa.Column('subtotal_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_type', sa.String(length=30), nullable=True),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_reason', sa.String(length=500), nullable=True),
    sa.Column('discount_status', sa.String(length=30), nullable=True),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_staff_id'], ['users.id'], name=op.f('fk_orders_created_by_staff_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], name=op.f('fk_orders_outlet_id_outlets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['basket_sessions.id'], name=op.f('fk_orders_session_id_basket_sessions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_outlet_id'), ['outlet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_session_id'), ['session_id'], unique=False)

    op.create_table('staff_audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=True),
    sa.Column('outlet_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('reference_type', sa.String(length=100), nullable=True),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], name=op.f('fk_staff_audit_log_outlet_id_outlets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('fk_staff_audit_log_staff_id_staff'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_audit_log'))
    )
    with op.batch_alter_table('staff_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_audit_log_outlet_id'), ['outlet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_audit_log_staff_id'), ['staff_id'], unique=False)

    op.create_table('abandoned_carts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('outlet_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('basket_number', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('total_estimate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('converted_order_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['converted_order_id'], ['orders.id'], name=op.f('fk_abandoned_carts_converted_order_id_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], name=op.f('fk_abandoned_carts_outlet_id_outlets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['basket_sessions.id'], name=op.f('fk_abandoned_carts_session_id_basket_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_abandoned_carts'))
    )
    with op.batch_alter_table('abandoned_carts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_abandoned_carts_outlet_id'), ['outlet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_abandoned_carts_session_id'), ['session_id'], unique=False)

    op.create_table('bill_discount_approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('discount_type', sa.String(length=30), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason_note', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_bill_discount_approvals_approved_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_bill_discount_approvals_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_bill_discount_approvals_requested_by_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bill_discount_approvals'))
    )
    with op.batch_alter_table('bill_discount_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bill_discount_approvals_order_id'), ['order_id'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('menu_item_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('added_by_staff_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=True),
    sa.Column('is_complimentary', sa.Boolean(), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax_category', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['added_by_staff_id'], ['users.id'], name=op.f('fk_order_items_added_by_staff_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name=op.f('fk_order_items_menu_item_id_menu_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['menu_item_variants.id'], name=op.f('fk_order_items_variant_id_menu_item_variants'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_added_by_staff_id'), ['added_by_staff_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)

    op.create_table('stock_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('outlet_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('change_type', sa.Enum('INTAKE', 'AUTO_DEDUCTION', 'MANUAL_ADJUSTMENT', 'RESTOCK', name='stockchangetypeenum'), nullable=False),
    sa.Column('quantity_change', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('resulting_stock', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('reference_order_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('unit_cost_snapshot', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_stock_ledger_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], name=op.f('fk_stock_ledger_item_id_inventory_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], name=op.f('fk_stock_ledger_outlet_id_outlets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reference_order_id'], ['orders.id'], name=op.f('fk_stock_ledger_reference_order_id_orders'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_ledger'))
    )
    with op.batch_alter_table('stock_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_ledger_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_ledger_outlet_id'), ['outlet_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_ledger_outlet_id'))
        batch_op.drop_index(batch_op.f('ix_stock_ledger_item_id'))

    op.drop_table('stock_ledger')
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_added_by_staff_id'))

    op.drop_table('order_items')
    with op.batch_alter_table('bill_discount_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bill_discount_approvals_order_id'))

    op.drop_table('bill_discount_approvals')
    with op.batch_alter_table('abandoned_carts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_abandoned_carts_session_id'))
        batch_op.drop_index(batch_op.f('ix_abandoned_carts_outlet_id'))

    op.drop_table('abandoned_carts')
    with op.batch_alter_table('staff_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_audit_log_staff_id'))
        batch_op.drop_index(batch_op.f('ix_staff_audit_log_outlet_id'))

    op.drop_table('staff_audit_log')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_session_id'))
        batch_op.drop_index(batch_op.f('ix_orders_outlet_id'))

    op.drop_table('orders')
    with op.batch_alter_table('menu_item_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_item_variants_menu_item_id'))

    op.drop_table('menu_item_variants')
    with op.batch_alter_table('menu_item_recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_item_recipes_menu_item_id'))
        batch_op.drop_index(batch_op.f('ix_menu_item_recipes_inventory_item_id'))

    op.drop_table('menu_item_recipes')
    with op.batch_alter_table('stock_intakes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_intakes_outlet_id'))
        batch_op.drop_index(batch_op.f('ix_stock_intakes_item_id'))
        batch_op.drop_index(batch_op.f('ix_stock_intakes_expiry_date'))
        batch_op.drop_index(batch_op.f('ix_stock_intakes_batch_number'))

    op.drop_table('stock_intakes')
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_outlet_id'))
        batch_op.drop_index(batch_op.f('ix_staff_email'))

    op.drop_table('staff')
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_items_outlet_id'))
        batch_op.drop_index(batch_op.f('ix_menu_items_inventory_item_id'))
        batch_op.drop_index(batch_op.f('ix_menu_items_category_id'))
        batch_op.drop_index(batch_op.f('ix_menu_items_barcode'))

    op.drop_table('menu_items')
    with op.batch_alter_table('basket_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_basket_sessions_session_key'))
        batch_op.drop_index(batch_op.f('ix_basket_sessions_outlet_id'))

    op.drop_table('basket_sessions')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_outlet_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_outlet_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_outlet_id'))

    op.drop_table('suppliers')
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_items_outlet_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_items_barcode'))

    op.drop_table('inventory_items')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_outlet_id'))

    op.drop_table('customers')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_outlet_id'))

    op.drop_table('categories')
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_events_event_id'))

    op.drop_table('webhook_events')
    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outlets_slug'))

    op.drop_table('outlets')
    # ### end Alembic commands ###
